# restored-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: restored-pvc
  annotations:
    dev.okteto.com/from-snapshot-id: "snap-09268276be35c338a"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: okteto-snapshot-sc
  resources:
    requests:
      storage: 1Gi