apiVersion: v1
kind: Pod
metadata:
  name: restored-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["cat /demo/data/sample-file.txt && sleep 3000"]
    volumeMounts:
    - name: restored-data
      mountPath: /demo/data
  volumes:
  - name: restored-data
    persistentVolumeClaim:
      claimName: restored-pvc
      readOnly: false